recipe:
  name: "MCP Server Configuration"
  description: "Set up Model Context Protocol servers for this project"

variables:
  mcp_config_file:
    value: "${project_root}/.mcp.json"
  mcp_catalog_file:
    value: "${recipe_dir}/mcp-catalog.yaml"
  generate_script:
    value: "${recipe_dir}/helpers/generate-mcp-config.sh"
  selected_servers:
    prompt: "Which MCP servers would you like to install?"
    type: "multi_choice"
    choices_from:
      file: "${mcp_catalog_file}"
      path: "mcp_servers"
      id_field: "_key"  # Special: use the YAML key as ID
      label_field: "name"
      description_field: "description"
      defaults: ["sequential-thinking", "filesystem"]  # Default selections

steps:
  - name: "Check existing configuration"
    type: "check_file"
    config:
      path: "${mcp_config_file}"
      if_exists: "ask_backup"

  - name: "Generate MCP configuration"
    type: "run_command"
    config:
      command: "${generate_script}"
      args: ["${mcp_catalog_file}", "${selected_servers}", "${mcp_config_file}"]
      working_dir: "${recipe_dir}"

post_setup:
  message: |
    ✅ MCP servers configured for this project!
    
    Configuration: ${mcp_config_file}
    Selected servers: ${selected_servers}
    
    To customize server configurations, edit the ${mcp_config_file} file.
    Restart Claude Code to activate the servers.