[manager]
prepend_keymap = [
  { on = "E", run = 'shell "nvim ." --block', desc = "Open current directory in neovim" },
  { on = ["c", "m"], run = 'plugin chmod', desc = "Chmod on selected files" },
  { on = "T", run = 'plugin toggle-pane max-preview', desc = "Maximize or restore preview pane" },
  { on = ["g", "r"] , run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"', desc = "Go to git root" },
  { on = "<C-p>" , run = 'shell -- qlmanage -p "$@"', desc = "Preview in the macos quicklook" },
]

[input]
prepend_keymap = [
  { on = "<Esc>", run = 'close', desc = "Cancel input" },
]
